In [3]:
import torch

In [21]:
x = torch.arange(12)
torch.randn(3, 4)

tensor([[ 0.6986, -1.9879,  3.4541,  0.1189],
        [-0.1523,  0.9260,  1.4336,  1.8629],
        [ 0.3500,  0.1894, -1.3234,  0.7714]])

In [20]:
x.reshape(3,4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [15]:
x[-1],x[1:3]

(tensor(11), tensor([1, 2]))

In [23]:
x = torch.arange(12)
x = x.reshape(3,4)
x[1, 2]=9
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  9,  7],
        [ 8,  9, 10, 11]])

In [25]:
x[0:2, :] = 12
x

tensor([[12, 12, 12, 12],
        [12, 12, 12, 12],
        [ 8,  9, 10, 11]])

#### 运算符

In [27]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x+y, x-y, x*y, x/y, x ** y # **是求幂运算 

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [28]:
torch.exp(x)  #求以e为底的指数函数

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

## 节省内存

In [49]:
Y=8
X=1
before = id(Y)
Y=Y+X
id(Y) == before

False

In [46]:
# 为了不引起内存的重新分配，可以使用切片表示法
X=torch.arange(6)
Y=torch.arange(6)
Z= torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X+Y
print('id(Z):', id(Z))
Y, Z

id(Z): 2288762707440
id(Z): 2288762707440


(tensor([0, 1, 2, 3, 4, 5]), tensor([ 0,  2,  4,  6,  8, 10]))

In [54]:
before = id(X)
X += Y
id(X) == before

False

In [57]:
X=torch.arange(6)
A = X.numpy()
B = torch.tensor(A) # 转化为torch中的张量
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [59]:
a=torch.tensor([3.5])
a, a.item(), float(a), int(a) #把张量转化为python标量的一些trick,比如.item()

(tensor([3.5000]), 3.5, 3.5, 3)

### 练习

In [65]:
Y= torch.arange(6)+1
X, Y, X<Y

(tensor([0, 1, 2, 3, 4, 5]),
 tensor([1, 2, 3, 4, 5, 6]),
 tensor([True, True, True, True, True, True]))